FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# MicroMOOC Subscription API

This executable document will describe the structure of the response for the user subscription API for MicroMOOC. Currently this API will just support GET queries. 

## Subscriptions [/users/{userId}/subscriptions/?f={format}]

### List an user Susbscription [GET]

+ Response 200 (application/json)

        [
            {
                "UserId": "userexample@outlook.com",
                "subscriptionName": "Enterprise",
                "expirationDate": "2020-08-05T08:40:51.620Z",
                "Privileges": {
                    "edx": [
                        {
                            "name": "Introduction to Artificial Intelligence",
                            "code": "DAT263x",
                            "organization": {
                                "displayName": "Microsoft",
                                "key": "microsoft"
                            },
                            "Programs": [
                                "Microsoft Professional Program in Artificial Intelligence"
                            ]
                        },{
                            "name": "Improving your usage of Python for Artificial Intelligence",
                            "code": "PYAI201",
                            "organization": {
                                "displayName": "MicroMOOC",
                                "key": "micromooc"
                            },
                            "Programs": [
                                "MicroMOOC Certificate for Pythons Skills",
                                "Other MicroMOOC Program"
                            ]
                        }
                    ],
                    "Coupon": [
                        {
                        
                        }
                    ] 
                }
            }
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }