FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# MicroMOOC Subscription API

This executable document will describe the structure of the response for the user subscription API for MicroMOOC. Currently this API will just support GET queries. 

## Subscriptions [/users/{userId}/subscriptions/?catalog=edx]

### List an user Susbscription [GET]

+ Response 200 (application/json)

        {
            "userId": "userexample@outlook.com",
            "subscriptions": [{
                "catalog": "edx",
                "name": "edx courses",
                "code": "edx_mpp",
                "icon": "https://{some_url_prefix}/{image_name}.png",
                "description": "free level of edx courses...",
                "provider": [{
                    "key": "microsoft",
                    "displayName": "Microsoft",
                    "logo": "https://{some_url_prefix}/{image_name}.png"
                }],
                "privileges": [{
                    "courseName":"Introduction to Artificial Intelligence",
                    "courseCode":"AI263x"
                    },{
                    "courseName":"Introduction to Big Data",
                    "courseCode":"DAT263x"
                    }]
                }
            ]
        }

+ Response 202 (application/json)

        {
            "message": "The request has been accepted for processing, but the processing has not been completed",
            "code": 202
        }

+ Response 301

    + Headers

            Location: http://my-sample-domain.com//users/{userId}/subscriptions/?catalog=edx

+ Response 302

    + Headers

            Location: http://my-sample-domain.com//users/{userId}/subscriptions/?catalog=edx

+ Response 400 (application/json)

        {
            "message": "Invalid request，invalid parameter",
            "code": 400
        }

+ Response 401 (application/json)

        {
            "message": "unauthorized. your credentials are not valid",
            "code": 401
        }


+ Response 404 (application/json)

        {
            "message": "The requested resource could not be found",
            "code": 404
        }

+ Response 500 (application/json)

        {
            "message": "Internal Server Error",
            "code": 500
        }

+ Response 505 (application/json)

        {
            "message": "HTTP Version Not Supported",
            "code": 505
        }

## Subscriptions [/users/{userId}/subscriptions/services/?catalog=edx]

### the valid services for user [GET]

+ Response 200 (application/json)

        {
            "userId": "userexample@outlook.com",
            "services": [{
                "catalog": "edx",
                "name": "edx courses",
                "code": "edx_mpp",
                "icon": "https://{some_url_prefix}/{image_name}.png",
                "description": "free level of edx courses...",
                "provider": [{
                    "key": "microsoft",
                    "displayName": "Microsoft",
                    "logo": "https://{some_url_prefix}/{image_name}.png"
                }],
                "privileges": [{
                    "courseName":"Introduction to Artificial Intelligence",
                    "courseCode":"AI263x",
                },{
                    "courseName":"Introduction to Big Data",
                    "courseCode":"DAT263x",
                },
                ]
            }]
        }
